apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: triton-ingress
spec:
  tls:
  - hosts:
    - cafe.example.com
    secretName: cafe-secret
  rules:
  - host: triton-http.f5demo.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "triton-inference-server.fullname" . }}
            port:
              number: 8000
  - host: triton-grpc.f5demo.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "triton-inference-server.fullname" . }}
            port:
              number: 8001
  - host: triton-metrics.f5demo.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "triton-inference-server.fullname" . }}
            port:
              number: 8002