apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-models-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/triton-models
    type: DirectoryOrCreate